# Generated by Django 3.2.4 on 2021-07-13 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(blank=True, max_length=25, verbose_name='username')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='nickname')),
                ('profile_image', models.ImageField(blank=True, upload_to=users.models.get_user_profile_path, verbose_name='profile image')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('introduce', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='phone')),
                ('gender', models.IntegerField(choices=[(0, '비공개'), (1, '남자'), (2, '여자')], default=0, verbose_name='gender')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
